---
 hosts: all
  become: yes
  tasks:
- name: Install Pi-hole
      shell: curl -sSL https://install.pi-hole.net | bash
    - name: Change Pi-hole HTTP port
      lineinfile:
        path: /etc/lighttpd/external.conf
        regexp: '^(server.port)'
        line: 'server.port := 8088'
    - name: Restart lighttpd
      service:
      name: lighttpd
      state: restarted